name: XPUtils
version: '1.0'
main: org.dotpast.XPUtils
api-version: '1.20'
commands:
  exportxp:
    description: Export XP into bottles
    usage: /<command> (amount/all)
    aliases:
      - exportexp
  currentxp:
    description: Show current XP
    usage: /<command>
    aliases:
      - currentexp
